---
name: tensorflow

instance_groups:
- name: tensorflow
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: tensorflow
    release: tensorflow
    properties: {}

variables: []

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: tensorflow
  version: 0.1.0
  url: https://github.com/starkandwayne/tensorflow-boshrelease/releases/download/v0.1.0/tensorflow-0.1.0.tgz
  sha1: 97da91063b5d3a94d063cc70493d9a8d7a58ed43
